# Docs: https://aka.ms/yaml
name: $(Build.DefinitionName)_$(Date:yyyyMMdd))
pr:
- master

trigger:
  batch: true
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: false
    steps:
    - powershell: .\bootstrap.ps1
   
    - task: Pester@8
      inputs:
          scriptFolder: '$(System.DefaultWorkingDirectory)\tests\*'
          resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
          run32Bit: False

    - task: PublishTestResults@2
      inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: '**/TEST-*.xml'
              testRunTitle: 'Publish test results'